### ISSUE TITLE
type hierarchy of ClosestPoint does not represent intent

### ISSUE THREAD

**Issue by marcelluethi** [unibas-gravis/scalismo#201]
Currently a result of a closestPoint operation can be either of type ```ClosestPoint```, which indicates that only the closest point and the distance was computed, or one of the subclasses ```ClosestPointIsVertex``` , ```ClosestPointOnLine``` or ```ClosestPointInTriangle```, which also provide access to meta data. 

However, these types should all be distinct and ```ClosestPoint``` should not be the base class, but rather a separate type, in order to make it possible to understand from the type signature, which information is available.

**Comment by Andreas-Forster** [comment]
As already indicated in the timeline this issue is fixed with the pull request #203.

`ClosestPointOnSurface` is introduced as new base class of `ClosestPointIsVertex`, `ClosestPointOnLine` and `ClosestPointInTriangle`. This class is not derived from `ClosestPoint`.

This makes it more clear that the function `getClosestPoint` and `getClosestPointOnSurface` in `MeshOperations` return different types and hence also different information.
