### ISSUE TITLE
adding attributes to the shape model

### ISSUE THREAD

**Issue by Ghazi-Bouabene** [unibas-gravis/scalismo#228]
It would be useful if one could combine some additional attributes, such as the subject's age, weight, height, gender, or even some properties of the shape itself, e.g. length or width of the bone, together with the shape model. 

An example use case of such a combined model would be to complete a fractured bone by conditioning the model, not only on the observed healthy part, but additionally on the patient's attributes: age, weight, length of the contralateral bone , etc., which should improve the completion results.

The method presented in this paper https://link.springer.com/chapter/10.1007/978-3-319-64870-5_5  could for example be used in the implementation (generalized to all shapes, not just faces).

**Comment by BernhardEgger** [comment]
I like the idea to include such a method and would be willing to contribute. Our work (link above) presents the model and includes an evaluation using model metrics. It does not include an analysis application besides attribute prediction. Besides the implementation, I think there should be an example application/paper that proves the usefulness in an analysis setting.
Compared to other methods to include attributes, the proposed one can also include categorical data which is often available in a clinical setting.
There seems to be a demand in the community and a range of applications:
- "Statistical model based shape prediction from a combination of
direct observations and various surrogates: application to orthopaedic research." by Blanc et al. 2012 (implemented as part of statismo)
- "Patient metadata-constrained shape models for cardiac image segmentation." by Pereañez et al. 2015
- https://groups.google.com/forum/#!topic/scalismo/GDDTKabMTLc

**Comment by BernhardEgger** [comment]
I don't know how well the method of Remi Blanc fits into Scalismo. For the copula method, it is definitely possible to squeeze it in. It, however, breaks with some ideas the framework was originally built on - the dependency structure is built on values that have no more a "meaning". 
The overhead in Scalismo is more a decision that should be done on a high-level. The alternative would be to provide the implementation as a separate project.
Since the applicability of both methods is quite wide, I would argue to put it as part of the Scalismo framework.

**Comment by marcelluethi** [comment]
As this issue has been inactive for a long time, I am closing it. In case there is still interest, we can open a new issue once we start with the implementation.
