### ISSUE TITLE
VantagePointTree.findEpsilonNeighbours fails when the point is in the tree

### ISSUE THREAD

**Issue by gilcu2** [unibas-gravis/scalismo#274]
The next test because when the objective point is already in the tree.If I put a point not in the tree works ok
```
it should "find the points in a ball around excluding himself" in {

    Given("some points")
    val points = Seq(
      RNDensePoint(0, 0),
      RNDensePoint(0, 1),
      RNDensePoint(0, 2)
    )

    And("the tree with the points")
    val tree = VantagePointTree(points, RNDensePoint.euclidean)

    And("an objetive point")
    val objetive = RNDensePoint(0, 1)

    And("the ball radio")
    val radio = 4.0

    And("the expected results")
    val expected = Set(
      RNDensePoint(0, 0),
      RNDensePoint(0, 1),
      RNDensePoint(0, 2)
    )

    When("the tree find points in the ball")
    val closestPoints = tree.findEpsilonNeighbours(objetive, radio)

    Then("the nearest must be the expected")
    closestPoints.toSet shouldBe expected
  }
```

**Comment by sschoenborn** [comment]
I successfully reproduced this behavior. The query cannot deal with different points at equal distance to the objective point ([0, 0] and [0, 2] are both at distance 1 of [0, 1]). I identified the root cause to be a wrong ordering used in the query structure [here](https://github.com/unibas-gravis/scalismo/blob/2e693186366ac65f4b79a733ada6933e301ecd69/src/main/scala/scalismo/utils/VantagePointTree.scala#L75). A fix is currently being tested.
