### ISSUE TITLE
Difficulty visualizing Scalismo software on MacOs Ventura

### ISSUE THREAD

**Issue by sshetty03** [unibas-gravis/scalismo#410]
WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future.
I get this warning message when i try opening scalismolab.command file, and I believe this is the reason why I am unable to visualize the program. I can see there are 3 windows open in my dock (scalismo tutorial, scalismo viewer, scalismo code pane); however, the windows appear transparent to me. Let me know if anyone has faced this problem and has fixed it.

**Comment by marcelluethi** [comment]
ScalismoLab is not actively maintained anymore and we it may not work any longer on newer Macs. Since we wrote ScalismoLab, the Scala ecosystem has greatly improved. In the meantime, there are better way to get started with Scalismo than using ScalismoLab. We recommend that you use  VSCode and Scala-CLI as described here: https://scalismo.org/docs. Since version 0.91, the error you describe is fixed. Since version 0.92 (which was released a few days ago), it also works on Macs with an M1 and M2 processor.
