### ISSUE TITLE
software crashes trying to run tutorial 1

### ISSUE THREAD

**Issue by sshetty03** [unibas-gravis/scalismo#411]
I'm able to open scalismo, and I can see the imports loading. Before it finishes loading, the window closes and I get the following warning:
WARNING: Failed to load implementation from:dev.ludovic.netlib.blas.JNIBLAS
return java 8 instance
Let me know how I can solve this problem.

**Comment by marcelluethi** [comment]
The warning you see should not worry you. If the system cannot find the native blas libraries, it will use default ones (see [netlib java](https://github.com/luhenry/netlib) for more information. 

As you are saying that the datasets are loading, I suspect everything works and what is confusing you is that the ui closes at the end. This is because the last line in the tutorial is `ui.close()`. Does it work as expected if you remove that line?

**Comment by sshetty03** [comment]
yes, thank you!
